# -*- coding: utf-8 -*-
"""Sample_Streamlit.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BomiatbwOeO4Co7R7ta1uE4vxq0YbfhR
"""

!pip install streamlit

import streamlit as st

# Add a title to your web app
st.title("Simple Streamlit App")

# Add text to the app
st.write("This is a simple Streamlit app.")

# Add a header
st.header("User Input")

# Add a text input field
user_input = st.text_input("Enter your name:", "Your Name")

# Display user input
st.write("Hello, " + user_input + "!")

# Add a sidebar
st.sidebar.header("Sidebar")
st.sidebar.write("You can add additional content here.")

# Add a plot or chart
import matplotlib.pyplot as plt
import numpy as np

st.subheader("Plot")
x = np.linspace(0, 10, 100)
y = np.sin(x)
plt.plot(x, y)
st.pyplot(plt)

# Add data display
st.subheader("Data Display")
st.dataframe({"Column 1": [1, 2, 3], "Column 2": [4, 5, 6]})

# Add a button
if st.button("Click Me"):
    st.write("Button clicked!")

# Add checkboxes
if st.checkbox("Show/Hide"):
    st.write("This content can be toggled.")

# Add selectbox
option = st.selectbox("Select an option:", ["Option 1", "Option 2", "Option 3"])
st.write("You selected:", option)

# Add radio buttons
radio_option = st.radio("Choose an option:", ["A", "B", "C"])
st.write("You chose:", radio_option)

